# Generated by Django 4.2.4 on 2023-11-06 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='day',
            name='color',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
