# Generated by Django 4.2.4 on 2023-09-16 05:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 17, 13, 41, 10, 23185)),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='start_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
