# Generated by Django 4.2.4 on 2023-09-13 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationimage',
            name='is_primary_image',
            field=models.BooleanField(default=False),
        ),
    ]
