# Generated by Django 4.2.4 on 2023-09-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_locationimage_is_primary_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accomodation',
            new_name='Accommodation',
        ),
        migrations.AddField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('1', 'Spot'), ('2', 'FoodPlace'), ('3', 'Accommodation')], default=1, max_length=1),
        ),
    ]
