# Generated by Django 4.2.4 on 2023-09-16 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_itinerary_end_date_itinerary_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='start_date',
        ),
    ]
