# Generated by Django 4.2.4 on 2023-11-06 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_day_options_day_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='color',
            field=models.CharField(default='#184E77', max_length=7),
        ),
    ]
