# Generated by Django 4.2.4 on 2023-08-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_location_description_location_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='image',
            field=models.ImageField(default='location_images/Background.jpg', upload_to='location_images/'),
        ),
    ]
