# Generated by Django 4.2.4 on 2023-09-13 10:07

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_accomodation_accommodation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationimage',
            name='image',
            field=models.ImageField(default='location_images/Background.jpg', upload_to=api.models.location_image_path),
        ),
    ]
