# Generated by Django 4.2.4 on 2023-09-17 08:45

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_itinerary_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationimage',
            name='image',
            field=models.ImageField(default='location_images/Background.jpg', max_length=512, upload_to=api.models.location_image_path),
        ),
    ]
