# Generated by Django 4.2.4 on 2023-08-20 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_tag_remove_spot_activity_focus_remove_spot_art_focus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.spot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'spot')},
            },
        ),
        migrations.AddField(
            model_name='spot',
            name='interested',
            field=models.ManyToManyField(related_name='bookmarks', through='api.Bookmark', to=settings.AUTH_USER_MODEL),
        ),
    ]
