# Generated by Django 4.2.4 on 2023-11-13 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_bookmark_datetime_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmark',
            options={'ordering': ['-datetime_created']},
        ),
    ]
