# Generated by Django 4.2.4 on 2023-08-31 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_ownership'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='location_food/')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.foodplace')),
            ],
        ),
    ]
