# Generated by Django 4.2.4 on 2023-09-24 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_customfee_spot'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraryitem',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.day'),
        ),
    ]
