# Generated by Django 4.2.4 on 2023-09-13 01:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='set_preferences',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.BooleanField(default=False)),
                ('historical', models.BooleanField(default=False)),
                ('activity', models.BooleanField(default=False)),
                ('outdoors', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
