# Generated by Django 4.2.4 on 2023-11-15 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_day_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
