# Generated by Django 4.2.4 on 2023-11-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_day_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
