# Generated by Django 4.2.4 on 2023-09-24 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_itineraryitem_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraryitem',
            name='day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.day'),
        ),
    ]
