# Generated by Django 4.2.4 on 2023-10-20 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_itineraryitem_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraryitem',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
