# Generated by Django 4.2.4 on 2023-11-18 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_day_completed_remove_day_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='day',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='day',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
