# Generated by Django 4.2.4 on 2023-10-21 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_itineraryitem_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itineraryitem',
            options={'ordering': ['order']},
        ),
    ]
