# Generated by Django 4.2.4 on 2023-10-27 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_itineraryitem_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preferences',
            old_name='historical',
            new_name='culture',
        ),
        migrations.RenameField(
            model_name='preferences',
            old_name='outdoors',
            new_name='history',
        ),
        migrations.RenameField(
            model_name='preferences',
            old_name='religious',
            new_name='religion',
        ),
    ]
